[package]
name = "css"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = { version = "0.19.2", features = ["png"] }
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false
